backend:
  - changed-files:
    - any-glob-to-any-file: 
      - 'netra/**/*.py'
      - 'poetry.lock'
      - 'pyproject.toml'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'netra/static/**'

docker:
  - changed-files:
    - any-glob-to-any-file: 
      - 'Dockerfile'
      - '**/*.Dockerfile'
      - 'docker-compose.yml'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - '.github/**'

tests:
  - changed-files:
    - any-glob-to-any-file: 'netra/tests/**'
